name: Monitor specs

on:
  schedule:
    - cron: '0 0 1 */2 *'
  workflow_dispatch:

jobs:
  find-specs:
    name: Update the list of monitored specs and highlights those that have changed
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest version of release script
      uses: actions/checkout@v4

    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check specs that changed since last review
      run: node src/monitor-specs.js --update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
