name: "NPM release: Request review of pre-release PR"

on:
  schedule:
    - cron: '0 5 * * 4'
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest version of release script
      uses: actions/checkout@v3

    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Request review of pre-release PR
      run: node src/request-pr-review.js
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}